[server]
headless = true
enableCORS = false
enableXsrfProtection = true
# If your host requires a specific port:
# port = 8501

# If you’re serving behind a reverse proxy at a subpath:
# baseUrlPath = "kmz"

# Reduce noisy logs:
# [logger]
# level = "info"  # options: "error", "warning", "info", "debug"
